title: The Wonders of Async Asset Streaming

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  A blog post dedicated to my adventures working on system to asynchronously load resources for a game engine.
  Santiago Bernadino - Gmail: santibberna@gmail.com

# If you clone the Minima repo and build locally, use this setting.
theme: minima