title: Santiago's Portfolio
author:
  name: Santiago Bernardino
  email: santibberna@gmail.com

description: >
  Game Programming. Portfolio website created by Santiago Bernardino. Consider checking out my work on Github if you have read this far.
  
remote_theme: jekyll/minima

show_excerpts: true

header_pages:
  - about.md
  - index.md

minima:
  skin: dark
  social_links:
  - { platform: github,         user_url: "https://github.com/SantiagoBerna" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/santiago-bernardino" }
  
  #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }